version: 2
name: "PyPyNum"
github_project: "PythonSJL/PyPyNum"
branch: "main"
use_directory: "."
index: "README.html"
build:
    os: "ubuntu-lts-latest"
    python: "3.x"
    commands:
        - echo "No build commands required"
